numpy
pandas
matplotlib
seaborn
scikit-learn
jupyterlab
jupyterlab-spellchecker
tqdm
ipython-autotime
ipywidgets
#pytest
#python-dotenv
pydantic
pydantic-settings
#------------------
#ucimlrepo
kagglehub
#------------------
#xgboost
#catboost
#-----------------
torch
torchvision

opencv-python
torchcodec
imageio
#torch-fidelity
#torchmetrics
torchinfo

#save model to draw it using netron
#onnx
#onnxscript

